### ISSUE TITLE
Footer section 

### ISSUE THREAD

**Issue by Waqibsk** [Majestic9169/metakgp-website#10]
We can add a footer section to the website ...which will contain... 
1. Contact list of the maintainers
2. Social media links 
3. Privacy policy 

here's  what i am thinking....

![Screenshot (23)](https://github.com/user-attachments/assets/31b29fb2-3a9f-4aed-81e5-1f6094ddbc5f)

Let me know if you have any feedback or suggestions :)

**Comment by Majestic9169** [comment]
This is a pretty good looking footer, if you could make the background a little softer or greyer it would be great!

Feel free to make this a pr

**Comment by Majestic9169** [comment]
Please also have a look at some of metakgp's standard footers as well. We usually keep them very simple like in [GYFT](gyft.metakgp.org)

**Comment by Waqibsk** [comment]
Here is the final look  with a few changes...

![Screenshot 2024-12-20 233233](https://github.com/user-attachments/assets/cc1dce8f-4feb-41cd-a9c1-45c959618531)

1. Changed the background 
2. To keep things simple removed the contact list and privacy policy section

**Comment by Majestic9169** [comment]
we don't have a discord so you can remove that and instead add whatsapp and linkedin

**Comment by Majestic9169** [comment]
Make this a PR and i'll merge
