### ISSUE TITLE
[Feature] Modify the landing page for MetaKGP

### ISSUE THREAD

**Issue by abhirajadhikary06** [Majestic9169/metakgp-website#8]
I want to modify the landing page for metaKGP. The README says that the current landing page looks janky, would like to modify the page for better visibility. 

- Add animations to the page
- Add github link and metaKGP link to the current projects showcased on the page
- remove the footer and add icons to social media pages

**Comment by Majestic9169** [comment]
I said that the current metakgp landing page looks janky, this project is meant to replace that website. If you want to contribute to that one then I suggest going to https://github.com/metakgp/metakgp.github.io, however i doubt it is being maintained
